version: '3.4'

services:
  frontend:
    image: moltimate-frontend
    container_name: moltimate-frontend
    restart: unless-stopped
    build:
      context: moltimate-frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./moltimate-frontend:/app

  backend:
    image: moltimate-backend
    container_name: moltimate-backend
    restart: unless-stopped
    build:
      context: moltimate-backend
      dockerfile: Dockerfile
      args:
        jarfile: target/moltimate-backend-0.0.1-SNAPSHOT.jar
    ports:
      - 8080:8080
